### ISSUE TITLE
Unexecutable test line

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/Payments#1]
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L18-L19
Exception is expected in line 18. So, line 19 will not be executed. Looks like it should be separate tests.

**Comment by Enfilde** [comment]
WHAT?It's not exception test ,so I can do as many assertions ,as i want ,KEK

**Comment by Enfilde** [comment]
And then not all exception tests ,only this kind https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L56
