### ISSUE TITLE
Test must check exceptions

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/Payments#2]
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L84
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L90
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L96
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L102
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L108
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/test/java/PaymentTest.java#L114
Current implementation of the test verifies only messages of exceptions and only of expected types.
It's better to catch any type of exception and verify that exception really was thrown and type of its type.

**Comment by Enfilde** [comment]
https://github.com/Enfilde/Payments/blob/ec6c9096ad5c248c2e57b7bc14e1859a8ad0685b/src/test/java/PaymentTest.java#L77-L86 Fixed
