### ISSUE TITLE
Public helper method

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Enfilde/Payments#3]
https://github.com/Enfilde/Payments/blob/9b681c3d24df42ea2c661aaad65a92ac8ffb1155/src/main/java/Organization.java#L24
Should this helper method be public?

**Comment by Enfilde** [comment]
https://github.com/Enfilde/Payments/blob/ec6c9096ad5c248c2e57b7bc14e1859a8ad0685b/src/main/java/Organization.java#L24-L28 Fixed
